background #15151a
foreground #e5e5f0
selection_background #202025
selection_foreground #e5e5f0
url_color #28a064
cursor #e5e5f0
cursor_text_color #15151a

# Tabs
active_tab_background #4a47ed
active_tab_foreground #0a0a15
inactive_tab_background #25252a
inactive_tab_foreground #c0c0e0
#tab_bar_background #0a0a15

# Windows
active_border_color #4a47ed
inactive_border_color #30303a

# normal
color0 #0a0a15
color1 #af3e59
color2 #28a064
color3 #938c05
color4 #4a47ed
color5 #723fc9
color6 #0895b5
color7 #c0c0e0

# bright
color8  #30303a
color9  #dc3e9d
color10 #3aa173
color11 #af623e
color12 #5475f7
color13 #a855f7
color14 #22b8d4
color15 #e5e5f0

# extended colors
color16 #af623e
color17 #dc3e9d

# settings
background_opacity 0.975

enable_audio_bell yes
visual_bell_duration 0.0

cursor_trail 1